name: chestxray_joint_new
channels:
  - conda-forge
  - pytorch
  - soumith
  - defaults
dependencies:
  - bleach=1.5.0=py36_0
  - cycler=0.10.0=py_2
  - cymem=1.31.2=py36_0
  - cytoolz=0.8.2=py36_0
  - dask-core=2.7.0=py_0
  - decorator=4.1.2=py36_0
  - dill=0.2.9=py36_0
  - expat=2.1.0=0
  - gst-plugins-base=1.8.0=0
  - gstreamer=1.8.0=0
  - html5lib=0.9999999=py36_0
  - imageio=2.6.1=py36_0
  - ipykernel=4.6.1=py36_0
  - ipython=6.1.0=py36_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.5.0=py_0
  - jinja2=2.9.6=py36_0
  - jpeg=9b=0
  - jsonschema=2.6.0=py36_0
  - jupyter_client=5.1.0=py36_0
  - jupyter_console=5.2.0=py36_0
  - jupyter_core=4.3.0=py36_0
  - libffi=3.2.1=1
  - libgcc=5.2.0=0
  - libiconv=1.14=0
  - libsodium=1.0.10=0
  - libxcb=1.12=1
  - markupsafe=1.0=py36_0
  - mistune=0.7.4=py36_0
  - mkl_random=1.0.4=py36hf2d7682_0
  - msgpack-python=0.4.8=py36_0
  - murmurhash=0.28.0=py36_0
  - nbformat=4.4.0=py36_0
  - networkx=2.2=py_0
  - notebook=5.0.0=py36_0
  - openssl=1.0.2l=0
  - pandocfilters=1.4.2=py36_0
  - path.py=10.3.1=py36_0
  - pexpect=4.2.1=py36_0
  - pickleshare=0.7.4=py36_0
  - pip=9.0.1=py36_1
  - plac=0.9.6=py_1
  - preshed=1.0.0=py36_0
  - prompt_toolkit=1.0.15=py36_0
  - ptyprocess=0.5.2=py36_0
  - pygments=2.2.0=py36_0
  - pyparsing=2.4.5=py_0
  - pyqt=5.6.0=py36_2
  - python-dateutil=2.6.1=py36_0
  - pytz=2017.2=py36_0
  - pywavelets=1.0.3=py36hd352d35_1
  - qtconsole=4.3.1=py36_0
  - regex=2017.11.09=py36_0
  - scikit-image=0.13.1=py36_0
  - six=1.12.0=py36_1000
  - sqlite=3.13.0=0
  - termcolor=1.1.0=py_2
  - terminado=0.6=py36_0
  - testpath=0.3.1=py36_0
  - toolz=0.9.0=py_1
  - tornado=4.5.2=py36_0
  - tqdm=4.32.2=py_0
  - traitlets=4.3.2=py36_0
  - ujson=1.35=py36_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5.1=py_1
  - wheel=0.29.0=py36_0
  - widgetsnbextension=3.5.0=py36_0
  - wrapt=1.10.11=py36_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.3=0
  - zeromq=4.1.5=0
  - zlib=1.2.11=0
  - _libgcc_mutex=0.1=main
  - absl-py=0.8.0=py36_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2019.11.27=0
  - certifi=2016.2.28=py36_0
  - cffi=1.12.3=py36h2e261b9_0
  - cmake=3.9.4=h142f0e9_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.0=cuda10.0_0
  - curl=7.55.1=hcb0b314_2
  - dbus=1.10.20=0
  - entrypoints=0.2.3=py36_0
  - fontconfig=2.12.1=3
  - freetype=2.5.5=2
  - glib=2.50.2=1
  - grpcio=1.12.1=py36hdbcaa40_0
  - icu=54.1=0
  - intel-openmp=2019.4=243
  - jedi=0.10.2=py36_2
  - jupyter=1.0.0=py36_3
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.30=1
  - libprotobuf=3.9.2=hd408876_0
  - libssh2=1.8.0=h8c220ad_2
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.9=he85c1e1_1
  - libuv=1.26.0=h7b6447c_0
  - libxml2=2.9.4=0
  - markdown=3.1.1=py36_0
  - matplotlib=2.0.2=np113py36_0
  - mkl=2019.4=243
  - mkl-include=2019.4=243
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.0.14=py36ha843d7b_0
  - nbconvert=5.2.1=py36_0
  - nccl=1.3.5=cuda10.0_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py36hfd86e86_0
  - numpy=1.13.3=py36ha266831_3
  - numpy-base=1.17.2=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - pandas=0.25.3=py36he6710b0_0
  - pcre=8.39=1
  - pillow=4.2.1=py36_0
  - protobuf=3.9.2=py36he6710b0_0
  - pycparser=2.19=py36_0
  - python=3.6.2=0
  - pyyaml=5.1.2=py36h7b6447c_0
  - pyzmq=16.0.2=py36_0
  - qt=5.6.2=5
  - readline=6.2=2
  - rhash=1.3.5=hbf7ad62_1
  - scipy=1.3.1=py36h7c811a0_0
  - setuptools=36.5.0=py36he42e2e1_0
  - simplegeneric=0.8.1=py36_1
  - sip=4.18=py36_0
  - tensorboard=1.14.0=py36hf484d3e_0
  - tk=8.5.18=0
  - typing=3.6.4=py36_0
  - werkzeug=0.16.0=py_0
  - yaml=0.1.7=had09818_2
  - pytorch=1.2.0=py3.6_cuda10.0.130_cudnn7.6.2_0
  - torchvision=0.4.0=py36_cu100
  - pip:
    - attrs==19.1.0
    - awscli==1.16.188
    - blis==0.4.1
    - boto3==1.9.182
    - botocore==1.12.182
    - catalogue==1.0.0
    - chardet==3.0.4
    - click==7.1
    - colorama==0.3.9
    - conllu==1.3.1
    - dask==2.7.0
    - docutils==0.14
    - en-core-sci-md==0.2.5
    - future==0.17.1
    - gitdb==4.0.5
    - gitpython==3.1.3
    - idna==2.8
    - importlib-metadata==1.7.0
    - jmespath==0.9.4
    - joblib==0.13.2
    - nmslib==1.8.1
    - opencv-python==4.2.0.32
    - pyasn1==0.4.5
    - pybind11==2.3.0
    - pyrsistent==0.15.2
    - pysbd==0.2.3
    - pytorch-transformers==1.0.0
    - requests==2.22.0
    - rsa==3.4.2
    - s3transfer==0.2.1
    - scikit-learn==0.21.2
    - scispacy==0.2.5
    - sentencepiece==0.1.82
    - smmap==3.0.4
    - spacy==2.3.1
    - srsly==1.0.2
    - thinc==7.4.1
    - torch==1.2.0
    - urllib3==1.25.6
    - wasabi==0.7.0
    - zipp==3.1.0

